firewall:
  hosts: 
    dc5pg_asa:
      ansible_host: 10.0.6.254
      ansible_network_os: asa
      ansible_connection: network_cli
      ansible_user: rancid
      ansible_password: "{{ rancid }}"
      ansible_become: true
      ansible_become_method: enable
      ansible_become_password: "{{ enable_pass }}"
